#!/bin/bash

echo "["
ls -la | grep .pdf |
    cut -d " " -f 6-10 |
    sed 's/\(^.*\)[ ]\+\(week[0-9]\{2\}-demo.pdf\)$/  {"url":"springnotes\/\2","modified":"\1"},/' |
    sed '$s/},/}/'
echo "]";
#offbyone
